//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MaHD { get; set; }
        public int MaMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual HoaDon HoaDon1 { get; set; }
        public virtual HoaDon HoaDon2 { get; set; }
        public virtual HoaDon HoaDon3 { get; set; }
        public virtual HoaDon HoaDon4 { get; set; }
        public virtual HoaDon HoaDon5 { get; set; }
        public virtual MonAn MonAn { get; set; }
        public virtual MonAn MonAn1 { get; set; }
        public virtual MonAn MonAn2 { get; set; }
        public virtual MonAn MonAn3 { get; set; }
        public virtual MonAn MonAn4 { get; set; }
        public virtual MonAn MonAn5 { get; set; }
    }
}
