//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonAn()
        {
            this.CTHDs = new HashSet<CTHD>();
            this.CTHDs1 = new HashSet<CTHD>();
            this.CTHDs2 = new HashSet<CTHD>();
            this.CTHDs3 = new HashSet<CTHD>();
            this.CTHDs4 = new HashSet<CTHD>();
            this.CTHDs5 = new HashSet<CTHD>();
        }
    
        public int MaMonAn { get; set; }
        public int MaLoai { get; set; }
        public string TenMonAn { get; set; }
        public Nullable<int> SLTonKho { get; set; }
        public Nullable<int> DonGia { get; set; }
        public byte[] HinhAnh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs5 { get; set; }
        public virtual LoaiMonAn LoaiMonAn { get; set; }
        public virtual LoaiMonAn LoaiMonAn1 { get; set; }
        public virtual LoaiMonAn LoaiMonAn2 { get; set; }
        public virtual LoaiMonAn LoaiMonAn3 { get; set; }
        public virtual LoaiMonAn LoaiMonAn4 { get; set; }
        public virtual LoaiMonAn LoaiMonAn5 { get; set; }
    }
}
