//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaLoaiTK { get; set; }
        public int MaLoai { get; set; }
        public int MaNV { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual LoaiTK LoaiTK { get; set; }
        public virtual LoaiTK LoaiTK1 { get; set; }
        public virtual LoaiTK LoaiTK2 { get; set; }
        public virtual LoaiTK LoaiTK3 { get; set; }
        public virtual LoaiTK LoaiTK4 { get; set; }
        public virtual LoaiTK LoaiTK5 { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        public virtual NhanVien NhanVien3 { get; set; }
        public virtual NhanVien NhanVien4 { get; set; }
        public virtual NhanVien NhanVien5 { get; set; }
    }
}
